title: "My Awesome Jekyll Site with Twitter Bootstrap"
email: me@example.com
description: >
  Just some stuff, you know?
baseurl: "/jekyll-twitter-bootstrap-template" # the subpath of your site, e.g. /blog
url: "https://me.github.io"
twitter_username: me
github_username:  me

# Build settings
source: source
destination: public
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM # Githup Flavoured Markdown
  hard_wrap: false

highlighter: pygments
lsi: false
# paginate: 15
